dist: trusty
language: java
jdk:
  - openjdk11
install: true
script:
  mvn clean test -Dtravis.buildNumber=$TRAVIS_BUILD_NUMBER -Dtravis.buildURL=$TRAVIS_BUILD_WEB_URL -Dtravis.branch=$TRAVIS_BRANCH
after_script:
  - chmod 777 .travis/deploy.sh
  - .travis/deploy.sh